# netlify.toml

[build]
  command = "npm run build"
  publish = "build"

# 1) Statisztikus assetek
[[redirects]]
  from   = "/static/*"
  to     = "/static/:splat"
  status = 200
  force  = false

# 2) Auth-végpontok proxy
[[redirects]]
  from    = "/register"
  to      = "http://ec2-16-171-241-40.eu-north-1.compute.amazonaws.com/register"
  status  = 200
  force   = true
  methods = ["POST","OPTIONS"]

[[redirects]]
  from    = "/login"
  to      = "http://ec2-16-171-241-40.eu-north-1.compute.amazonaws.com/login"
  status  = 200
  force   = true
  methods = ["POST","OPTIONS"]

[[redirects]]
  from    = "/logout"
  to      = "http://ec2-16-171-241-40.eu-north-1.compute.amazonaws.com/logout"
  status  = 200
  force   = true
  methods = ["POST","OPTIONS"]

# 3) API-hívások proxy
[[redirects]]
  from   = "/api/*"
  to     = "http://ec2-16-171-241-40.eu-north-1.compute.amazonaws.com/api/:splat"
  status = 200
  force  = true

# 4) Képek (storage) proxy
[[redirects]]
  from   = "/storage/*"
  to     = "http://ec2-16-171-241-40.eu-north-1.compute.amazonaws.com/storage/:splat"
  status = 200
  force  = true

# 5) SPA-fallback (minden más -> index.html)
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
  force  = true
